const express = require('express')
const route = express.Router()
const contactController = require('../controller/contactController')
const auth =  require('../middlewares/auth')
route.post('/', auth, contactController.addContact)
route.get('/', auth, contactController.getContacts)
route.get('/:mailId', auth, contactController.getContactlById)
route.patch('/:id', auth, contactController.editContact)
route.delete('/:id', auth, contactController.deleteContact)
module.exports = route